// 统一的词库数据中心 (vocabData.js) - 绝对并集版 (基础 + CCG + HSK/YCT)
const CATEGORIES = {
  animals: {
    id: 'animals', name: '动物', nameEn: 'Animals', icon: './zoo.png',
    items: [
      { id: 'cat', hanzi: '猫', pinyin: 'māo', emoji: '🐱', en: 'cat', isCore: true, isCCG: true },
      { id: 'dog', hanzi: '狗', pinyin: 'gǒu', emoji: '🐶', en: 'dog', isCore: true, isCCG: true },
      { id: 'bird', hanzi: '鸟', pinyin: 'niǎo', emoji: '🐦', en: 'bird', isCore: true, isCCG: true },
      { id: 'fish', hanzi: '鱼', pinyin: 'yú', emoji: '🐟', en: 'fish', isCore: true, isCCG: true },
      { id: 'horse', hanzi: '马', pinyin: 'mǎ', emoji: '🐴', en: 'horse', isCore: true, isCCG: true },
      { id: 'panda', hanzi: '熊猫', pinyin: 'xióng māo', emoji: '🐼', en: 'panda', isCore: true, isCCG: true },
      { id: 'tiger', hanzi: '老虎', pinyin: 'lǎo hǔ', emoji: '🐯', en: 'tiger', isCore: true, isCCG: true },
      { id: 'cow_ox', hanzi: '牛', pinyin: 'niú', emoji: '🐮', en: 'cow,ox', isCore: true, isCCG: true },
      { id: 'sheep', hanzi: '羊', pinyin: 'yáng', emoji: '🐑', en: 'sheep', isCore: true, isCCG: true },
      { id: 'camel', hanzi: '骆驼', pinyin: 'luò tuó', emoji: '🐫', en: 'camel', isCore: true, isCCG: true },
      { id: 'chicken', hanzi: '鸡', pinyin: 'jī', emoji: '🐔', en: 'chicken', isCore: true, isCCG: false },
      { id: 'duck', hanzi: '鸭', pinyin: 'yā', emoji: '🦆', en: 'duck', isCore: true, isCCG: false },
      { id: 'rabbit', hanzi: '兔子', pinyin: 'tù zi', emoji: '🐰', en: 'rabbit', isCore: true, isCCG: true },
      { id: 'bear', hanzi: '熊', pinyin: 'xióng', emoji: '🐻', en: 'bear', isCore: true, isCCG: false },
      { id: 'monkey', hanzi: '猴子', pinyin: 'hóu zi', emoji: '🐵', en: 'monkey', isCore: true, isCCG: true },
      { id: 'elephant', hanzi: '大象', pinyin: 'dà xiàng', emoji: '🐘', en: 'elephant', isCore: true, isCCG: true },
      { id: 'shark', hanzi: '鲨鱼', pinyin: 'shā yú', emoji: '🦈', en: 'shark', isCore: false, isCCG: true },
      { id: 'whale', hanzi: '鲸鱼', pinyin: 'jīng yú', emoji: '🐳', en: 'whale', isCore: false, isCCG: true },
      { id: 'turtle', hanzi: '乌龟', pinyin: 'wū guī', emoji: '🐢', en: 'turtle', isCore: true, isCCG: true },
 { id: 'goldfish', hanzi: '金鱼', pinyin: 'jīn yú', emoji: '🐟', img: './goldfish.png', en: 'goldfish', isCore: true, isCCG: true },
      { id: 'dolphin', hanzi: '海豚', pinyin: 'hǎi tún', emoji: '🐬', en: 'dolphin', isCore: false, isCCG: true },
      { id: 'parrot', hanzi: '鹦鹉', pinyin: 'yīng wǔ', emoji: '🦜', en: 'parrot', isCore: false, isCCG: true },
      { id: 'falcon', hanzi: '猎隼', pinyin: 'liè sǔn', emoji: '🦅', img: './falcon.png',  en: 'falcon', isCore: false, isCCG: true },
      { id: 'antelope', hanzi: '羚羊', pinyin: 'líng yáng', emoji: '🦌', en: 'antelope', isCore: false, isCCG: true },
      { id: 'lion', hanzi: '狮子', pinyin: 'shī zi', emoji: '🦁', en: 'lion', isCore: true, isCCG: true },
      { id: 'ant', hanzi: '蚂蚁', pinyin: 'mǎ yǐ', emoji: '🐜', en: 'ant', isCore: true, isCCG: true },
      { id: 'gorilla', hanzi: '猩猩', pinyin: 'xīng xing', emoji: '🦍', en: 'gorilla', isCore: true, isCCG: true },
      { id: 'giraffe', hanzi: '长颈鹿', pinyin: 'cháng jǐng lù', emoji: '🦒', en: 'giraffe', isCore: true, isCCG: true },
      { id: 'leopard', hanzi: '豹', pinyin: 'bào', emoji: '🐆', en: 'leopard', isCore: false, isCCG: true },
      { id: 'wolf', hanzi: '狼', pinyin: 'láng', emoji: '🐺', en: 'wolf', isCore: false, isCCG: true },
      { id: 'eagle', hanzi: '鹰', pinyin: 'yīng', emoji: '🦅', en: 'eagle', isCore: false, isCCG: true }
    ]
  },
  fruits: {
    id: 'fruits', name: '水果', nameEn: 'Fruits', icon: '🍎',
    items: [
      { id: 'apple', hanzi: '苹果', pinyin: 'píng guǒ', emoji: '🍎', en: 'apple', isCore: true, isCCG: true },
      { id: 'banana', hanzi: '香蕉', pinyin: 'xiāng jiāo', emoji: '🍌', en: 'banana', isCore: true, isCCG: true },
      { id: 'grape', hanzi: '葡萄', pinyin: 'pú tao', emoji: '🍇', en: 'grape', isCore: true, isCCG: true },
      { id: 'watermelon', hanzi: '西瓜', pinyin: 'xī guā', emoji: '🍉', en: 'watermelon', isCore: true, isCCG: true },
      { id: 'strawberry', hanzi: '草莓', pinyin: 'cǎo méi', emoji: '🍓', en: 'strawberry', isCore: true, isCCG: true },
      { id: 'orange', hanzi: '橙子', pinyin: 'chéng zi', emoji: '🍊', en: 'orange', isCore: true, isCCG: true },
      { id: 'peach', hanzi: '桃子', pinyin: 'táo zi', emoji: '🍑', en: 'peach', isCore: true, isCCG: false },
      { id: 'pineapple', hanzi: '菠萝', pinyin: 'bō luó', emoji: '🍍', en: 'pineapple', isCore: false, isCCG: false },
      { id: 'pear', hanzi: '梨', pinyin: 'lí', emoji: '🍐', en: 'pear', isCore: true, isCCG: false },
      { id: 'cherry', hanzi: '樱桃', pinyin: 'yīng táo', emoji: '🍒', en: 'cherry', isCore: false, isCCG: false },
      { id: 'green_apple', hanzi: '青苹果', pinyin: 'qīng píng guǒ', emoji: '🍏', en: 'green apple', isCore: true, isCCG: false },
      { id: 'avocado', hanzi: '牛油果', pinyin: 'niú yóu guǒ', emoji: '🥑', en: 'avocado', isCore: false, isCCG: false },
      { id: 'coconut', hanzi: '椰子', pinyin: 'yē zi', emoji: '🥥', en: 'coconut', isCore: false, isCCG: false },
      { id: 'kiwi', hanzi: '猕猴桃', pinyin: 'mí hóu táo', emoji: '🥝', en: 'kiwi', isCore: false, isCCG: false },
      { id: 'blueberry', hanzi: '蓝莓', pinyin: 'lán méi', emoji: '🫐', en: 'blueberry', isCore: true, isCCG: false },
      { id: 'melon', hanzi: '甜瓜', pinyin: 'tián guā', emoji: '🍈', en: 'melon', isCore: true, isCCG: false },
      { id: 'dates', hanzi: '椰枣', pinyin: 'yē zǎo', emoji: '🌴', en: 'dates', isCore: false, isCCG: true },
      { id: 'lemon', hanzi: '柠檬', pinyin: 'níng méng', emoji: '🍋', en: 'lemon', isCore: true, isCCG: true }
    ]
  },
  vegetables: {
    id: 'vegetables', name: '蔬菜', nameEn: 'Vegetables', icon: '🥦',
    items: [
      { id: 'cabbage', hanzi: '白菜', pinyin: 'bái cài', emoji: '🥬', en: 'cabbage', isCore: true, isCCG: false },
      { id: 'potato', hanzi: '土豆', pinyin: 'tǔ dòu', emoji: '🥔', en: 'potato', isCore: true, isCCG: true },
      { id: 'tomato', hanzi: '西红柿', pinyin: 'xī hóng shì', emoji: '🍅', en: 'tomato', isCore: true, isCCG: true },
      { id: 'carrot', hanzi: '胡萝卜', pinyin: 'hú luó bo', emoji: '🥕', en: 'carrot', isCore: false, isCCG: true },
      { id: 'broccoli', hanzi: '西兰花', pinyin: 'xī lán huā', emoji: '🥦', en: 'broccoli', isCore: false, isCCG: false },
      { id: 'onion', hanzi: '洋葱', pinyin: 'yáng cōng', emoji: '🧅', en: 'onion', isCore: false, isCCG: true },
      { id: 'mushroom', hanzi: '蘑菇', pinyin: 'mó gu', emoji: '🍄', en: 'mushroom', isCore: false, isCCG: false },
      { id: 'eggplant', hanzi: '茄子', pinyin: 'qié zi', emoji: '🍆', en: 'eggplant', isCore: false, isCCG: true },
      { id: 'cucumber', hanzi: '黄瓜', pinyin: 'huáng guā', emoji: '🥒', en: 'cucumber', isCore: true, isCCG: true },
      { id: 'pumpkin', hanzi: '南瓜', pinyin: 'nán guā', emoji: '🎃', en: 'pumpkin', isCore: false, isCCG: false },
      { id: 'pepper', hanzi: '辣椒', pinyin: 'là jiāo', emoji: '🌶️', en: 'pepper', isCore: true, isCCG: false },
      { id: 'corn', hanzi: '玉米', pinyin: 'yù mǐ', emoji: '🌽', en: 'corn', isCore: false, isCCG: false },
      { id: 'garlic', hanzi: '大蒜', pinyin: 'dà suàn', emoji: '🧄', en: 'garlic', isCore: true, isCCG: false },
      { id: 'peanut', hanzi: '花生', pinyin: 'huā shēng', emoji: '🥜', en: 'peanut', isCore: true, isCCG: false },
      { id: 'sweet_potato', hanzi: '红薯', pinyin: 'hóng shǔ', emoji: '🍠', en: 'sweet potato', isCore: true, isCCG: false },
      { id: 'pea', hanzi: '豌豆', pinyin: 'wān dòu', emoji: '🫛', en: 'pea', isCore: true, isCCG: false }
    ]
  },
  food: {
    id: 'food', name: '食物和饮料', nameEn: 'Food and Beverage', icon: '🍔',
    items: [
      { id: 'bread', hanzi: '面包', pinyin: 'miàn bāo', emoji: '🍞', en: 'bread', isCore: true, isCCG: false },
      { id: 'rice', hanzi: '米饭', pinyin: 'mǐ fàn', emoji: '🍚', en: 'rice', isCore: true, isCCG: true },
      { id: 'noodles', hanzi: '面条', pinyin: 'miàn tiáo', emoji: '🍜', en: 'noodles', isCore: true, isCCG: true },
      { id: 'dumplings', hanzi: '饺子', pinyin: 'jiǎo zi', emoji: '🥟', en: 'dumplings', isCore: true, isCCG: true },
      { id: 'hamburger1', hanzi: '汉堡', pinyin: 'hàn bǎo', emoji: '🍔', en: 'hamburger', isCore: true, isCCG: false },
      { id: 'hamburger2', hanzi: '汉堡包', pinyin: 'hàn bǎo bāo', emoji: '🍔', en: 'hamburger', isCore: false, isCCG: true },
      { id: 'pizza1', hanzi: '披萨', pinyin: 'pī sà', emoji: '🍕', en: 'pizza', isCore: true, isCCG: false },
      { id: 'pizza2', hanzi: '比萨饼', pinyin: 'bǐ sà bǐng', emoji: '🍕', en: 'pizza', isCore: false, isCCG: true },
      { id: 'hot_dog', hanzi: '热狗', pinyin: 'rè gǒu', emoji: '🌭', en: 'hot dog', isCore: true, isCCG: false },
      { id: 'egg', hanzi: '鸡蛋', pinyin: 'jī dàn', emoji: '🥚', en: 'egg', isCore: true, isCCG: true },
      { id: 'cake', hanzi: '蛋糕', pinyin: 'dàn gāo', emoji: '🍰', en: 'cake', isCore: true, isCCG: true },
      { id: 'ice_cream1', hanzi: '冰淇淋', pinyin: 'bīng qí lín', emoji: '🍦', en: 'ice cream', isCore: true, isCCG: false },
      { id: 'ice_cream2', hanzi: '冰激凌', pinyin: 'bīng jī líng', emoji: '🍦', en: 'ice cream', isCore: false, isCCG: true },
      { id: 'milk', hanzi: '牛奶', pinyin: 'niú nǎi', emoji: '🥛', en: 'milk', isCore: true, isCCG: true },
      { id: 'juice', hanzi: '果汁', pinyin: 'guǒ zhī', emoji: '🧃', en: 'juice', isCore: true, isCCG: true },
      { id: 'soup', hanzi: '汤', pinyin: 'tāng', emoji: '🥣', en: 'soup', isCore: true, isCCG: true },
      { id: 'meat', hanzi: '肉', pinyin: 'ròu', emoji: '🥩', en: 'meat', isCore: true, isCCG: false },
      { id: 'candy', hanzi: '糖果', pinyin: 'táng guǒ', emoji: '🍬', en: 'candy', isCore: true, isCCG: false },
      { id: 'cookie', hanzi: '饼干', pinyin: 'bǐng gān', emoji: '🍪', en: 'cookie', isCore: true, isCCG: false },
      { id: 'water', hanzi: '水', pinyin: 'shuǐ', emoji: '🫗', en: 'water', isCore: true, isCCG: true },
      { id: 'tea', hanzi: '茶', pinyin: 'chá', emoji: '🍵', en: 'tea', isCore: true, isCCG: true },
      { id: 'coffee', hanzi: '咖啡', pinyin: 'kā fēi', emoji: '☕', en: 'coffee', isCore: true, isCCG: true },
      { id: 'beer', hanzi: '啤酒', pinyin: 'pí jiǔ', emoji: '🍺', en: 'beer', isCore: true, isCCG: false },
      { id: 'fried_rice', hanzi: '炒饭', pinyin: 'chǎo fàn', emoji: '🍛', img: './fried_rice.png', en: 'fried rice', isCore: false, isCCG: false },
      { id: 'fried_noodles', hanzi: '炒面', pinyin: 'chǎo miàn', emoji: '🍝', img: './fried_noodles.png', en: 'fried noodles', isCore: false, isCCG: false },
      { id: 'fried_chicken', hanzi: '炸鸡', pinyin: 'zhá jī', emoji: '🍗', en: 'fried chicken', isCore: false, isCCG: false },
      { id: 'roast_duck', hanzi: '烤鸭', pinyin: 'kǎo yā', emoji: '🍖', img: './roast_duck.png', en: 'roast duck', isCore: false, isCCG: false },
      { id: 'salad', hanzi: '沙拉', pinyin: 'shā lā', emoji: '🥗', en: 'salad', isCore: false, isCCG: true },
      { id: 'sushi', hanzi: '寿司', pinyin: 'shòu sī', emoji: '🍣', en: 'sushi', isCore: false, isCCG: false },
      { id: 'sugar', hanzi: '糖', pinyin: 'táng', emoji: '⬜', img: './sugar.png', en: 'sugar', isCore: true, isCCG: false },
      { id: 'sandwich', hanzi: '三明治', pinyin: 'sān míng zhì', emoji: '🥪', en: 'sandwich', isCore: false, isCCG: true },
      { id: 'chocolate', hanzi: '巧克力', pinyin: 'qiǎo kè lì', emoji: '🍫', en: 'chocolate', isCore: true, isCCG: true },
      { id: 'cola', hanzi: '可乐', pinyin: 'kě lè', emoji: '🥤', en: 'cola', isCore: true, isCCG: true },
      { id: 'steamed_bun', hanzi: '包子', pinyin: 'bāo zi', emoji: '🥟', img: './steamed_bun.png', en: 'steamed bun', isCore: true, isCCG: true },
      { id: 'chinese_food', hanzi: '中国菜', pinyin: 'zhōng guó cài', emoji: '🥢', en: 'Chinese food', isCore: true, isCCG: true },
      { id: 'beef', hanzi: '牛肉', pinyin: 'niú ròu', emoji: '🐂', en: 'beef', isCore: true, isCCG: true },
      { id: 'mutton', hanzi: '羊肉', pinyin: 'yáng ròu', emoji: '🐏', en: 'mutton', isCore: true, isCCG: true },
      { id: 'seafood', hanzi: '海鲜', pinyin: 'hǎi xiān', emoji: '🦞', en: 'seafood', isCore: true, isCCG: true }
    ]
  },
  colors: {
    id: 'colors', name: '颜色', nameEn: 'Colors', icon: '🎨',
    items: [
      { id: 'red', hanzi: '红色', pinyin: 'hóng sè', emoji: '🔴', en: 'red', isCore: true, isCCG: true },
      { id: 'blue', hanzi: '蓝色', pinyin: 'lán sè', emoji: '🔵', en: 'blue', isCore: true, isCCG: true },
      { id: 'yellow', hanzi: '黄色', pinyin: 'huáng sè', emoji: '🟡', en: 'yellow', isCore: true, isCCG: true },
      { id: 'green', hanzi: '绿色', pinyin: 'lǜ sè', emoji: '🟢', en: 'green', isCore: true, isCCG: true },
      { id: 'black', hanzi: '黑色', pinyin: 'hēi sè', emoji: '⚫', en: 'black', isCore: true, isCCG: true },
      { id: 'white', hanzi: '白色', pinyin: 'bái sè', emoji: '⚪', en: 'white', isCore: true, isCCG: true },
      { id: 'purple', hanzi: '紫色', pinyin: 'zǐ sè', emoji: '🟣', en: 'purple', isCore: true, isCCG: true },
      { id: 'brown', hanzi: '棕色', pinyin: 'zōng sè', emoji: '🟤', en: 'brown', isCore: false, isCCG: false },
      { id: 'gray', hanzi: '灰色', pinyin: 'huī sè', emoji: '🔘', en: 'gray', isCore: false, isCCG: false },
      { id: 'pink', hanzi: '粉色', pinyin: 'fěn sè', emoji: '🩷', en: 'pink', isCore: true, isCCG: true },
      { id: 'orange', hanzi: '橙色', pinyin: 'chéng sè', emoji: '🟠', en: 'orange', isCore: true, isCCG: true },
      { id: 'color_word', hanzi: '颜色', pinyin: 'yán sè', emoji: '🎨', en: 'color', isCore: true, isCCG: true }
    ]
  },
  family: {
    id: 'family', name: '家庭成员', nameEn: 'Family', icon: '👨‍👩‍👧‍👦',
    items: [
      { id: 'dad', hanzi: '爸爸', pinyin: 'bà ba', emoji: '👨‍🍼', en: 'dad', isCore: true, isCCG: true },
      { id: 'mom', hanzi: '妈妈', pinyin: 'mā ma', emoji: '👩‍🍼', en: 'mom', isCore: true, isCCG: true },
      { id: 'grandpa', hanzi: '爷爷', pinyin: 'yé ye', emoji: '👴', en: 'grandpa', isCore: true, isCCG: true },
      { id: 'grandma', hanzi: '奶奶', pinyin: 'nǎi nai', emoji: '👵', en: 'grandma', isCore: true, isCCG: true },
      { id: 'older_brother', hanzi: '哥哥', pinyin: 'gē ge', emoji: '👨‍🦱', en: 'older brother', isCore: true, isCCG: true },
      { id: 'older_sister', hanzi: '姐姐', pinyin: 'jiě jie', emoji: '👩‍🦰', en: 'older sister', isCore: true, isCCG: true },
      { id: 'younger_brother', hanzi: '弟弟', pinyin: 'dì di', emoji: '👦', en: 'younger brother', isCore: true, isCCG: true },
      { id: 'younger_sister', hanzi: '妹妹', pinyin: 'mèi mei', emoji: '👧', en: 'younger sister', isCore: true, isCCG: true },
      { id: 'uncle', hanzi: '叔叔', pinyin: 'shū shu', emoji: '🙋‍♂️', en: 'uncle', isCore: true, isCCG: true },
      { id: 'aunt', hanzi: '阿姨', pinyin: 'ā yí', emoji: '🙋‍♀️', en: 'aunt', isCore: true, isCCG: true },
      { id: 'child', hanzi: '孩子', pinyin: 'hái zi', emoji: '👶', en: 'child', isCore: true, isCCG: true },
      { id: 'son', hanzi: '儿子', pinyin: 'ér zi', emoji: '👦🏻', en: 'son', isCore: true, isCCG: false },
      { id: 'daughter', hanzi: '女儿', pinyin: 'nǚ ér', emoji: '👧🏻', en: 'daughter', isCore: true, isCCG: false },
      { id: 'everyone', hanzi: '大家', pinyin: 'dà jiā', emoji: '👪', en: 'everyone', isCore: true, isCCG: true }
    ]
  },
  vehicles: {
    id: 'vehicles', name: '交通工具', nameEn: 'Vehicles', icon: '🚗',
    items: [
      { id: 'car', hanzi: '汽车', pinyin: 'qì chē', emoji: '🚗', en: 'car', isCore: true, isCCG: true },
      { id: 'bus', hanzi: '公交车', pinyin: 'gōng jiāo chē', emoji: '🚍', en: 'bus', isCore: true, isCCG: true },
      { id: 'train', hanzi: '火车', pinyin: 'huǒ chē', emoji: '🚂', en: 'train', isCore: true, isCCG: true },
      { id: 'plane', hanzi: '飞机', pinyin: 'fēi jī', emoji: '✈️', en: 'plane', isCore: true, isCCG: true },
      { id: 'boat', hanzi: '船', pinyin: 'chuán', emoji: '🛶', en: 'boat', isCore: true, isCCG: true },
      { id: 'bike', hanzi: '自行车', pinyin: 'zì xíng chē', emoji: '🚲', en: 'bike', isCore: true, isCCG: true },
      { id: 'police_car', hanzi: '警车', pinyin: 'jǐng chē', emoji: '🚓', en: 'police car', isCore: true, isCCG: true },
      { id: 'ambulance', hanzi: '救护车', pinyin: 'jiù hù chē', emoji: '🚑', en: 'ambulance', isCore: true, isCCG: false },
      { id: 'taxi', hanzi: '出租车', pinyin: 'chū zū chē', emoji: '🚕', en: 'taxi', isCore: true, isCCG: true },
      { id: 'subway', hanzi: '地铁', pinyin: 'dì tiě', emoji: '🚇', en: 'subway', isCore: true, isCCG: true },
      { id: 'motorcycle', hanzi: '摩托车', pinyin: 'mó tuō chē', emoji: '🏍️', en: 'motorcycle', isCore: false, isCCG: false },
      { id: 'truck', hanzi: '卡车', pinyin: 'kǎ chē', emoji: '🚚', en: 'truck', isCore: true, isCCG: false },
      { id: 'fire_engine', hanzi: '消防车', pinyin: 'xiāo fáng chē', emoji: '🚒', en: 'fire engine', isCore: true, isCCG: true },
      { id: 'helicopter', hanzi: '直升机', pinyin: 'zhí shēng jī', emoji: '🚁', en: 'helicopter', isCore: true, isCCG: false },
      { id: 'tractor', hanzi: '拖拉机', pinyin: 'tuō lā jī', emoji: '🚜', en: 'tractor', isCore: true, isCCG: false },
      { id: 'scooter', hanzi: '滑板车', pinyin: 'huá bǎn chē', emoji: '🛴', en: 'scooter', isCore: true, isCCG: false },
      { id: 'school_bus', hanzi: '校车', pinyin: 'xiào chē', emoji: '🚌', en: 'school bus', isCore: true, isCCG: true },
      { id: 'high_speed_train', hanzi: '高铁', pinyin: 'gāo tiě', emoji: '🚄', en: 'high speed train', isCore: true, isCCG: true },
      { id: 'ship', hanzi: '轮船', pinyin: 'lún chuán', emoji: '🚢', en: 'ship', isCore: true, isCCG: true }
    ]
  },
  weather: {
    id: 'weather_and_seasons', name: '天气', nameEn: 'Weather and Seasons', icon: '🌦️',
    items: [
      { id: 'sunny', hanzi: '晴天', pinyin: 'qíng tiān', emoji: '☀️', en: 'sunny', isCore: true, isCCG: true },
     { id: 'rainy', hanzi: '下雨', pinyin: 'xià yǔ', emoji: '🌧️', en: 'rainy', isCore: true, isCCG: true },
      { id: 'cloudy', hanzi: '阴天', pinyin: 'yīn tiān', emoji: '☁️', img: './cloudy.png', en: 'cloudy', isCore: true, isCCG: true },
     { id: 'snowy', hanzi: '下雪', pinyin: 'xià xuě', emoji: '❄️', en: 'snowy', isCore: true, isCCG: false },
      { id: 'windy', hanzi: '刮风', pinyin: 'guā fēng', emoji: '🌀', en: 'windy', isCore: true, isCCG: true },
      { id: 'thunder', hanzi: '打雷', pinyin: 'dǎ léi', emoji: '🌩️', en: 'thunder', isCore: true, isCCG: false },
      { id: 'lightning', hanzi: '闪电', pinyin: 'shǎn diàn', emoji: '⚡', en: 'lightning', isCore: true, isCCG: false },
      { id: 'rainbow', hanzi: '彩虹', pinyin: 'cǎi hóng', emoji: '🌈', en: 'rainbow', isCore: true, isCCG: false },
      { id: 'partly_cloudy', hanzi: '多云', pinyin: 'duō yún', emoji: '⛅', en: 'partly cloudy', isCore: true, isCCG: true },
      { id: 'foggy', hanzi: '有雾', pinyin: 'yǒu wù', emoji: '🌫️', en: 'foggy', isCore: false, isCCG: true },
      { id: 'tornado', hanzi: '龙卷风', pinyin: 'lóng juǎn fēng', emoji: '🌪️', en: 'tornado', isCore: true, isCCG: false },
      { id: 'umbrella', hanzi: '雨伞', pinyin: 'yǔ sǎn', emoji: '☔', en: 'umbrella', isCore: true, isCCG: true },
      { id: 'weather_word', hanzi: '天气', pinyin: 'tiān qì', emoji: '🌦️', en: 'weather', isCore: true, isCCG: false },
      { id: 'spring', hanzi: '春天', pinyin: 'chūn tiān', emoji: '🌼', en: 'spring', isCore: false, isCCG: true },
      { id: 'summer', hanzi: '夏天', pinyin: 'xià tiān', emoji: '🍹', en: 'summer', isCore: false, isCCG: true },
      { id: 'autumn', hanzi: '秋天', pinyin: 'qiū tiān', emoji: '🍂', en: 'autumn', isCore: false, isCCG: true },
      { id: 'winter', hanzi: '冬天', pinyin: 'dōng tiān', emoji: '☃️', en: 'winter', isCore: false, isCCG: true },
      { id: 'sky', hanzi: '天空', pinyin: 'tiān kōng', emoji: '🌌', en: 'sky', isCore: false, isCCG: true },
      { id: 'sun', hanzi: '太阳', pinyin: 'tài yáng', emoji: '🌞', en: 'sun', isCore: false, isCCG: true },
      { id: 'moon', hanzi: '月亮', pinyin: 'yuè liang', emoji: '🌛', en: 'moon', isCore: false, isCCG: true },
      { id: 'star', hanzi: '星星', pinyin: 'xīng xing', emoji: '⭐', en: 'star', isCore: false, isCCG: true },
      { id: 'cloud', hanzi: '云', pinyin: 'yún', emoji: '☁️', en: 'cloud', isCore: false, isCCG: true },
      { id: 'sandstorm', hanzi: '沙尘暴', pinyin: 'shā chén bào', emoji: '🌪️', img:'./sandstorm.png', en: 'sandstorm', isCore: false, isCCG: true }
    ]
  },
  clothing: {
    id: 'clothing', name: '服装', nameEn: 'Clothing', icon: '👚',
    items: [
      { id: 'shirt', hanzi: '衬衫', pinyin: 'chèn shān', emoji: '👔', en: 'shirt', isCore: true, isCCG: true },
      { id: 't_shirt', hanzi: 'T恤', pinyin: 'T xù', emoji: '👕', en: 'T-shirt', isCore: true, isCCG: false },
      { id: 'pants', hanzi: '裤子', pinyin: 'kù zi', emoji: '👖', en: 'pants', isCore: true, isCCG: true },
      { id: 'skirt', hanzi: '裙子', pinyin: 'qún zi', emoji: '👗', en: 'skirt', isCore: true, isCCG: true },
      { id: 'shoes', hanzi: '鞋子', pinyin: 'xié zi', emoji: '👞', en: 'shoes', isCore: true, isCCG: true },
      { id: 'hat', hanzi: '帽子', pinyin: 'mào zi', emoji: '🧢', en: 'hat', isCore: true, isCCG: false },
      { id: 'coat', hanzi: '外套', pinyin: 'wài tào', emoji: '🧥', en: 'coat', isCore: true, isCCG: false },
      { id: 'socks', hanzi: '袜子', pinyin: 'wà zi', emoji: '🧦', en: 'socks', isCore: true, isCCG: true },
      { id: 'glasses', hanzi: '眼镜', pinyin: 'yǎn jìng', emoji: '👓', en: 'glasses', isCore: true, isCCG: false },
      { id: 'scarf', hanzi: '围巾', pinyin: 'wéi jīn', emoji: '🧣', en: 'scarf', isCore: true, isCCG: false },
      { id: 'gloves', hanzi: '手套', pinyin: 'shǒu tào', emoji: '🧤', en: 'gloves', isCore: true, isCCG: false },
      { id: 'swimsuit', hanzi: '泳衣', pinyin: 'yǒng yī', emoji: '🩱', en: 'swimsuit', isCore: true, isCCG: false },
      { id: 'clothes', hanzi: '衣服', pinyin: 'yī fu', emoji: '👚', en: 'clothes', isCore: true, isCCG: false },
      { id: 'school_uniform', hanzi: '校服', pinyin: 'xiào fú', emoji: '👔', img: './school_uniform.png', en: 'school uniform', isCore: true, isCCG: true },
      { id: 'long_robe', hanzi: '长袍', pinyin: 'cháng páo', emoji: '👘', img: './robe.png', en: 'robe', isCore: true, isCCG: true },
      { id: 'headscarf', hanzi: '头巾', pinyin: 'tóu jīn', emoji: '🧕', en: 'headscarf', isCore: true, isCCG: true },
      { id: 'sandals', hanzi: '凉鞋', pinyin: 'liáng xié', emoji: '👡', en: 'sandals', isCore: true, isCCG: true },
      { id: 'tangzhuang', hanzi: '唐装', pinyin: 'táng zhuāng', emoji: '👚', img: './tangzhuang.png', en: 'Tang suit', isCore: false, isCCG: true },
      { id: 'hanfu', hanzi: '汉服', pinyin: 'hàn fú', emoji: '👚', img: './hanfu.png', en: 'Hanfu', isCore: false, isCCG: true },
      { id: 'bookmark', hanzi: '书签', pinyin: 'shū qiān', emoji: '🔖', en: 'bookmark', isCore: false, isCCG: true },
      { id: 'fan', hanzi: '扇子', pinyin: 'shàn zi', emoji: '🪭', en: 'fan', isCore: false, isCCG: true },
      { id: 'jacket', hanzi: '上衣', pinyin: 'shàng yī', emoji: '🧥', img: './jacket.png', en: 'jacket', isCore: false, isCCG: true },
      { id: 'sneakers', hanzi: '运动鞋', pinyin: 'yùn dòng xié', emoji: '👟', en: 'sneakers', isCore: true, isCCG: true }
    ]
  },
  places: {
    id: 'places', name: '地点', nameEn: 'Places', icon: '🏫',
    items: [
      { id: 'school', hanzi: '学校', pinyin: 'xué xiào', emoji: '🏫', en: 'school', isCore: true, isCCG: true },
      { id: 'hospital', hanzi: '医院', pinyin: 'yī yuàn', emoji: '🏥', en: 'hospital', isCore: true, isCCG: true },
      { id: 'park', hanzi: '公园', pinyin: 'gōng yuán', emoji: '🏞️', en: 'park', isCore: true, isCCG: true },
      { id: 'supermarket', hanzi: '超市', pinyin: 'chāo shì', emoji: '🛒', en: 'supermarket', isCore: true, isCCG: false },
      { id: 'home', hanzi: '家', pinyin: 'jiā', emoji: '🏠', en: 'home', isCore: true, isCCG: true },
      { id: 'bank', hanzi: '银行', pinyin: 'yín háng', emoji: '🏦', en: 'bank', isCore: true, isCCG: false },
      { id: 'restroom', hanzi: '洗手间', pinyin: 'xǐ shǒu jiān', emoji: '🚻', en: 'restroom', isCore: true, isCCG: true },
      { id: 'library', hanzi: '图书馆', pinyin: 'tú shū guǎn', emoji: '📖', en: 'library', isCore: true, isCCG: true },
      { id: 'cinema', hanzi: '电影院', pinyin: 'diàn yǐng yuàn', emoji: '🍿', en: 'cinema', isCore: true, isCCG: true },
      { id: 'train_station', hanzi: '火车站', pinyin: 'huǒ chē zhàn', emoji: '🚉', en: 'train station', isCore: true, isCCG: false },
      { id: 'airport', hanzi: '机场', pinyin: 'jī chǎng', emoji: '🛫', en: 'airport', isCore: true, isCCG: false },
      { id: 'zoo', hanzi: '动物园', pinyin: 'dòng wù yuán', emoji: '🎪', img: './zoo.png', en: 'zoo', isCore: true, isCCG: true },
      { id: 'gym', hanzi: '健身房', pinyin: 'jiàn shēn fáng', emoji: '🏋️', en: 'gym', isCore: true, isCCG: false },
      { id: 'bookstore', hanzi: '书店', pinyin: 'shū diàn', emoji: '📚', en: 'bookstore', isCore: true, isCCG: false },
      { id: 'cafe', hanzi: '咖啡馆', pinyin: 'kā fēi guǎn', emoji: '☕', en: 'cafe', isCore: true, isCCG: false },
      { id: 'store', hanzi: '商店', pinyin: 'shāng diàn', emoji: '🏪', en: 'store', isCore: true, isCCG: true },
      { id: 'company', hanzi: '公司', pinyin: 'gōng sī', emoji: '🏢', en: 'company', isCore: true, isCCG: false },
      { id: 'restaurant_ccg', hanzi: '饭店', pinyin: 'fàn diàn', emoji: '🍽️', en: 'restaurant', isCore: true, isCCG: true },
      { id: 'classroom', hanzi: '教室', pinyin: 'jiào shì', emoji: '👩‍🏫', en: 'classroom', isCore: true, isCCG: true },
      { id: 'room', hanzi: '房间', pinyin: 'fáng jiān', emoji: '🚪', en: 'room', isCore: true, isCCG: false },
      { id: 'hotel', hanzi: '宾馆', pinyin: 'bīn guǎn', emoji: '🏨', en: 'hotel', isCore: true, isCCG: false },
      { id: 'office', hanzi: '办公室', pinyin: 'bàn gōng shì', emoji: '💼', en: 'office', isCore: true, isCCG: false },
      { id: 'mall', hanzi: '商场', pinyin: 'shāng chǎng', emoji: '🛍️', en: 'shopping mall', isCore: true, isCCG: true },
      { id: 'seaside', hanzi: '海边', pinyin: 'hǎi biān', emoji: '🏖️', en: 'seaside', isCore: true, isCCG: true },
      { id: 'desert', hanzi: '沙漠', pinyin: 'shā mò', emoji: '🏜️', en: 'desert', isCore: true, isCCG: true },
      { id: 'garden', hanzi: '花园', pinyin: 'huā yuán', emoji: '🏵️', en: 'garden', isCore: true, isCCG: true },
      { id: 'museum', hanzi: '博物馆', pinyin: 'bó wù guǎn', emoji: '🏛️', en: 'museum', isCore: false, isCCG: true },
      { id: 'living_room', hanzi: '客厅', pinyin: 'kè tīng', emoji: '🏛️', img: './living_room.png', en: 'living room', isCore: false, isCCG: true },
      { id: 'bedroom', hanzi: '卧室', pinyin: 'wò shì', emoji: '🏛️', img: './bedroom.png', en: 'bedroom', isCore: false, isCCG: true },
      { id: 'kitchen', hanzi: '厨房', pinyin: 'chú fáng', emoji: '🏛️', img: './kitchen.png', en: 'kitchen', isCore: false, isCCG: true },
      { id: 'balcony', hanzi: '阳台', pinyin: 'yáng tái', emoji: '🏛️', img: './balcony.png', en: 'balcony', isCore: false, isCCG: true },
      { id: 'study_room', hanzi: '书房', pinyin: 'shū fáng', emoji: '🏛️', img: './study_room.png', en: 'study room', isCore: false, isCCG: true },
      { id: 'canteen', hanzi: '餐厅', pinyin: 'cān tīng', emoji: '🏛️', img: './canteen.png', en: 'canteen', isCore: false, isCCG: true },
      { id: 'subway_station', hanzi: '地铁站', pinyin: 'dì tiě zhàn', emoji: '🚇', en: 'subway station', isCore: false, isCCG: true },
      { id: 'mosque', hanzi: '清真寺', pinyin: 'qīng zhēn sì', emoji: '🕌', en: 'mosque', isCore: false, isCCG: true }
    ]
  },
  furniture: {
    id: 'furniture', name: '家具与文具', nameEn: 'Furniture and Stationery', icon: '🛏️',
    items: [
      { id: 'chair', hanzi: '椅子', pinyin: 'yǐ zi', emoji: '🪑', en: 'chair', isCore: true, isCCG: true },
      { id: 'table', hanzi: '桌子', pinyin: 'zhuō zi', emoji: '🏷️', img: './table.png', en: 'table', isCore: true, isCCG: true },
      { id: 'bed', hanzi: '床', pinyin: 'chuáng', emoji: '🛏️', en: 'bed', isCore: true, isCCG: false },
      { id: 'sofa', hanzi: '沙发', pinyin: 'shā fā', emoji: '🛋️', en: 'sofa', isCore: true, isCCG: false },
      { id: 'door', hanzi: '门', pinyin: 'mén', emoji: '🚪', en: 'door', isCore: true, isCCG: false },
      { id: 'window', hanzi: '窗户', pinyin: 'chuāng hu', emoji: '🪟', en: 'window', isCore: true, isCCG: false },
      { id: 'cabinet', hanzi: '柜子', pinyin: 'guì zi', emoji: '🗄️', en: 'cabinet', isCore: true, isCCG: true },
      { id: 'mirror', hanzi: '镜子', pinyin: 'jìng zi', emoji: '🪞', en: 'mirror', isCore: true, isCCG: false },
      { id: 'clock', hanzi: '钟', pinyin: 'zhōng', emoji: '🕰️', en: 'clock', isCore: true, isCCG: false },
      { id: 'painting', hanzi: '画', pinyin: 'huà', emoji: '🖼️', en: 'painting', isCore: true, isCCG: false },
      { id: 'trash_can', hanzi: '垃圾桶', pinyin: 'lā jī tǒng', emoji: '🗑️', en: 'trash can', isCore: true, isCCG: false },
      { id: 'bookshelf', hanzi: '书架', pinyin: 'shū jià', emoji: '🗃️', img: './bookshelf.png', en: 'bookshelf', isCore: true, isCCG: false },
      { id: 'sink', hanzi: '洗手池', pinyin: 'xǐ shǒu chí', emoji: '🚰', img: './sink.png', en: 'sink', isCore: true, isCCG: false },
      { id: 'toilet_seat', hanzi: '马桶', pinyin: 'mǎ tǒng', emoji: '🚽', en: 'toilet', isCore: true, isCCG: false },
      { id: 'rug', hanzi: '地毯', pinyin: 'dì tǎn', emoji: '🟥', img: './carpet.png', en: 'carpet', isCore: true, isCCG: false },
      { id: 'blackboard', hanzi: '黑板', pinyin: 'hēi bǎn', emoji: '⬛', img: './blackboard.png', en: 'blackboard', isCore: true, isCCG: false },
      { id: 'newspaper', hanzi: '报纸', pinyin: 'bào zhǐ', emoji: '📰', en: 'newspaper', isCore: true, isCCG: false },
      { id: 'pen', hanzi: '笔', pinyin: 'bǐ', emoji: '🖊️', en: 'pen', isCore: true, isCCG: false },
      { id: 'whiteboard', hanzi: '白板', pinyin: 'bái bǎn', emoji: '⬜', img: './whiteboard.png', en: 'whiteboard', isCore: true, isCCG: true },
      { id: 'schoolbag', hanzi: '书包', pinyin: 'shū bāo', emoji: '🎒', en: 'schoolbag', isCore: true, isCCG: true },
      { id: 'textbook', hanzi: '课本', pinyin: 'kè běn', emoji: '📖', en: 'textbook', isCore: true, isCCG: true },
      { id: 'notebook', hanzi: '本子', pinyin: 'běn zi', emoji: '📓', en: 'notebook', isCore: true, isCCG: true },
      { id: 'pencil', hanzi: '铅笔', pinyin: 'qiān bǐ', emoji: '✏️', en: 'pencil', isCore: true, isCCG: true },
      { id: 'eraser', hanzi: '橡皮', pinyin: 'xiàng pí', emoji: '🧼', img: './eraser.png', en: 'eraser', isCore: true, isCCG: true },
      { id: 'ruler', hanzi: '尺子', pinyin: 'chǐ zi', emoji: '📏', en: 'ruler', isCore: true, isCCG: true },
      { id: 'paper', hanzi: '纸', pinyin: 'zhǐ', emoji: '📄', en: 'paper', isCore: true, isCCG: true },
      { id: 'lunchbox', hanzi: '饭盒', pinyin: 'fàn hé', emoji: '🍱', en: 'lunchbox', isCore: true, isCCG: true },
      { id: 'plate', hanzi: '盘子', pinyin: 'pán zi', emoji: '🍽️', en: 'plate', isCore: true, isCCG: true },
      { id: 'cup', hanzi: '杯子', pinyin: 'bēi zi', emoji: '🥛', en: 'cup', isCore: true, isCCG: true },
      { id: 'spoon', hanzi: '勺子', pinyin: 'sháo zi', emoji: '🥄', en: 'spoon', isCore: true, isCCG: true },
      { id: 'chopsticks', hanzi: '筷子', pinyin: 'kuài zi', emoji: '🥢', en: 'chopsticks', isCore: true, isCCG: true },
      { id: 'pencil_case', hanzi: '笔袋', pinyin: 'bǐ dài', emoji: '👝', img: './pencil_case.png', en: 'pencil case', isCore: true, isCCG: true },
      { id: 'book', hanzi: '书', pinyin: 'shū', emoji: '📚', en: 'book', isCore: true, isCCG: true }
    ]
  },
  sports: {
    id: 'sports', name: '运动', nameEn: 'Sports', icon: '🏃‍',
    items: [
      { id: 'football', hanzi: '足球', pinyin: 'zú qiú', emoji: '⚽', en: 'football', isCore: true, isCCG: true },
      { id: 'basketball', hanzi: '篮球', pinyin: 'lán qiú', emoji: '🏀', en: 'basketball', isCore: true, isCCG: true },
      { id: 'play_football', hanzi: '踢足球', pinyin: 'tī zú qiú', emoji: '🥅', en: 'play football', isCore: false, isCCG: true },
      { id: 'play_basketball', hanzi: '打篮球', pinyin: 'dǎ lán qiú', emoji: '⛹️', en: 'play basketball', isCore: false, isCCG: true },
      { id: 'tennis', hanzi: '网球', pinyin: 'wǎng qiú', emoji: '🎾', en: 'tennis', isCore: true, isCCG: true },
      { id: 'ping_pong', hanzi: '乒乓球', pinyin: 'pīng pāng qiú', emoji: '🏓', en: 'ping pong', isCore: true, isCCG: true },
      { id: 'badminton', hanzi: '羽毛球', pinyin: 'yǔ máo qiú', emoji: '🏸', en: 'badminton', isCore: true, isCCG: false },
      { id: 'volleyball', hanzi: '排球', pinyin: 'pái qiú', emoji: '🏐', en: 'volleyball', isCore: true, isCCG: false },
      { id: 'baseball', hanzi: '棒球', pinyin: 'bàng qiú', emoji: '⚾', en: 'baseball', isCore: true, isCCG: false },
      { id: 'swimming', hanzi: '游泳', pinyin: 'yóu yǒng', emoji: '🏊', en: 'swimming', isCore: true, isCCG: true },
      { id: 'running', hanzi: '跑步', pinyin: 'pǎo bù', emoji: '🏃', en: 'running', isCore: true, isCCG: true },
      { id: 'cycling', hanzi: '骑车', pinyin: 'qí chē', emoji: '🚴', en: 'cycling', isCore: true, isCCG: false },
      { id: 'skiing', hanzi: '滑雪', pinyin: 'huá xuě', emoji: '🎿', en: 'skiing', isCore: true, isCCG: false },
      { id: 'skating', hanzi: '滑冰', pinyin: 'huá bīng', emoji: '⛸️', en: 'skating', isCore: true, isCCG: false },
      { id: 'boxing', hanzi: '拳击', pinyin: 'quán jī', emoji: '🥊', en: 'boxing', isCore: true, isCCG: false },
      { id: 'gymnastics', hanzi: '体操', pinyin: 'tǐ cāo', emoji: '🤸', en: 'gymnastics', isCore: true, isCCG: false },
      { id: 'golf', hanzi: '高尔夫', pinyin: 'gāo ěr fū', emoji: '⛳', en: 'golf', isCore: true, isCCG: false },
      { id: 'kung_fu', hanzi: '功夫', pinyin: 'gōng fu', emoji: '🥋', en: 'kung fu', isCore: true, isCCG: true }
    ]
  },
  electric_device: {
    id: 'electric_device', name: '电器', nameEn: 'Electric Device', icon: '🔌',
    items: [
      { id: 'computer', hanzi: '电脑', pinyin: 'diàn nǎo', emoji: '💻', en: 'computer', isCore: true, isCCG: true },
      { id: 'tv', hanzi: '电视', pinyin: 'diàn shì', emoji: '📺', en: 'tv', isCore: true, isCCG: true },
      { id: 'phone', hanzi: '手机', pinyin: 'shǒu jī', emoji: '📱', en: 'phone', isCore: true, isCCG: true },
      { id: 'camera', hanzi: '照相机', pinyin: 'zhào xiàng jī', emoji: '📷', en: 'camera', isCore: true, isCCG: false },
      { id: 'watch', hanzi: '手表', pinyin: 'shǒu biǎo', emoji: '⌚', en: 'watch', isCore: true, isCCG: false },
      { id: 'earphones_headphones', hanzi: '耳机', pinyin: 'ěr jī', emoji: '🎧', en: 'earphones/headphones', isCore: true, isCCG: false },
      { id: 'mouse', hanzi: '鼠标', pinyin: 'shǔ biāo', emoji: '🖱️', en: 'mouse', isCore: true, isCCG: false },
      { id: 'keyboard', hanzi: '键盘', pinyin: 'jiàn pán', emoji: '⌨️', en: 'keyboard', isCore: true, isCCG: false },
      { id: 'battery', hanzi: '电池', pinyin: 'diàn chí', emoji: '🔋', en: 'battery', isCore: true, isCCG: false },
      { id: 'telephone', hanzi: '电话', pinyin: 'diàn huà', emoji: '☎️', en: 'telephone', isCore: true, isCCG: true },
      { id: 'printer', hanzi: '打印机', pinyin: 'dǎ yìn jī', emoji: '🖨️', en: 'printer', isCore: true, isCCG: false },
      { id: 'gaming_machine', hanzi: '游戏机', pinyin: 'yóu xì jī', emoji: '🎮', en: 'gaming machine', isCore: true, isCCG: true },
      { id: 'microphone', hanzi: '麦克风', pinyin: 'mài kè fēng', emoji: '🎤', en: 'microphone', isCore: true, isCCG: false },
      { id: 'projector', hanzi: '投影仪', pinyin: 'tóu yǐng yí', emoji: '📽️', en: 'projector', isCore: true, isCCG: false },
      { id: 'fridge', hanzi: '冰箱', pinyin: 'bīng xiāng', emoji: '🧊', img: './fridge.png', en: 'fridge', isCore: false, isCCG: false },
      { id: 'air_conditioner', hanzi: '空调', pinyin: 'kōng tiáo', emoji: '❄️', img: './air_conditioner.png', en: 'air conditioner', isCore: false, isCCG: false },
      { id: 'plug', hanzi: '插头', pinyin: 'chā tóu', emoji: '🔌', en: 'plug', isCore: true, isCCG: false }
    ]
  },
  body_parts: {
    id: 'body_parts', name: '身体部位', nameEn: 'Body Parts', icon: '💪',
    items: [
      { id: 'head', hanzi: '头', pinyin: 'tóu', emoji: '👤', en: 'head', isCore: true, isCCG: true },
      { id: 'eye', hanzi: '眼睛', pinyin: 'yǎn jing', emoji: '👁️', en: 'eye', isCore: true, isCCG: true },
      { id: 'ear', hanzi: '耳朵', pinyin: 'ěr duo', emoji: '👂', en: 'ear', isCore: true, isCCG: true },
      { id: 'nose', hanzi: '鼻子', pinyin: 'bí zi', emoji: '👃', en: 'nose', isCore: true, isCCG: true },
      { id: 'mouth', hanzi: '嘴巴', pinyin: 'zuǐ ba', emoji: '👄', en: 'mouth', isCore: true, isCCG: true },
      { id: 'face', hanzi: '脸', pinyin: 'liǎn', emoji: '😊', en: 'face', isCore: true, isCCG: false },
      { id: 'hair', hanzi: '头发', pinyin: 'tóu fa', emoji: '💇', img: './hair.png', en: 'hair', isCore: true, isCCG: true },
      { id: 'hand', hanzi: '手', pinyin: 'shǒu', emoji: '✋', en: 'hand', isCore: true, isCCG: true },
      { id: 'foot', hanzi: '脚', pinyin: 'jiǎo', emoji: '🦶', en: 'foot', isCore: true, isCCG: true },
      { id: 'leg', hanzi: '腿', pinyin: 'tuǐ', emoji: '🦵', en: 'leg', isCore: true, isCCG: true },
      { id: 'shoulder', hanzi: '肩膀', pinyin: 'jiān bǎng', emoji: '💪', img: './shoulder.png', en: 'shoulder', isCore: true, isCCG: true },
      { id: 'knee', hanzi: '膝盖', pinyin: 'xī gài', emoji: '🦵', img: './knee.png', en: 'knee', isCore: true, isCCG: true },
      { id: 'arm', hanzi: '胳膊', pinyin: 'gē bo', emoji: '💪', en: 'arm', isCore: true, isCCG: true }
    ]
  },
  numbers: {
    id: 'numbers', name: '数字', nameEn: 'Numbers', icon: '🔢',
    items: [
      { id: 'zero', hanzi: '零', pinyin: 'líng', emoji: '0️⃣', en: 'zero', isCore: true, isCCG: false },
      { id: 'one', hanzi: '一', pinyin: 'yī', emoji: '1️⃣', en: 'one', isCore: true, isCCG: true },
      { id: 'two', hanzi: '二', pinyin: 'èr', emoji: '2️⃣', en: 'two', isCore: true, isCCG: true },
      { id: 'three', hanzi: '三', pinyin: 'sān', emoji: '3️⃣', en: 'three', isCore: true, isCCG: true },
      { id: 'four', hanzi: '四', pinyin: 'sì', emoji: '4️⃣', en: 'four', isCore: true, isCCG: true },
      { id: 'five', hanzi: '五', pinyin: 'wǔ', emoji: '5️⃣', en: 'five', isCore: true, isCCG: true },
      { id: 'six', hanzi: '六', pinyin: 'liù', emoji: '6️⃣', en: 'six', isCore: true, isCCG: true },
      { id: 'seven', hanzi: '七', pinyin: 'qī', emoji: '7️⃣', en: 'seven', isCore: true, isCCG: true },
      { id: 'eight', hanzi: '八', pinyin: 'bā', emoji: '8️⃣', en: 'eight', isCore: true, isCCG: true },
      { id: 'nine', hanzi: '九', pinyin: 'jiǔ', emoji: '9️⃣', en: 'nine', isCore: true, isCCG: true },
      { id: 'ten', hanzi: '十', pinyin: 'shí', emoji: '🔟', en: 'ten', isCore: true, isCCG: true },
      { id: 'hundred', hanzi: '百', pinyin: 'bǎi', emoji: '💯', en: 'hundred', isCore: true, isCCG: true }
    ]
  },
  time: {
    id: 'time', name: '时间', nameEn: 'Time', icon: '⏰',
    items: [
      { id: 'morning_early', hanzi: '早上', pinyin: 'zǎo shang', emoji: '🌅', en: 'early morning', isCore: true, isCCG: false },
      { id: 'morning', hanzi: '上午', pinyin: 'shàng wǔ', emoji: '☀️', en: 'morning', isCore: true, isCCG: true },
      { id: 'afternoon', hanzi: '下午', pinyin: 'xià wǔ', emoji: '🌄', en: 'afternoon', isCore: true, isCCG: true },
      { id: 'evening', hanzi: '晚上', pinyin: 'wǎn shang', emoji: '🌃', en: 'evening', isCore: true, isCCG: false },
      { id: 'noon', hanzi: '中午', pinyin: 'zhōng wǔ', emoji: '☀️', img: './noon.png', en: 'noon', isCore: false, isCCG: true },
      { id: 'daytime', hanzi: '白天', pinyin: 'bái tiān', emoji: '🌄', img: './daytime.png', en: 'daytime', isCore: false, isCCG: true },
      { id: 'Monday', hanzi: '星期一', pinyin: 'xīng qī yī', emoji: '🌄', img: './monday.png', en: 'Monday', isCore: false, isCCG: true },
      { id: 'Tuesday', hanzi: '星期二', pinyin: 'xīng qī èr', emoji: '🌄', img: './tuesday.png', en: 'Tuesday', isCore: false, isCCG: true },
      { id: 'Wednesday', hanzi: '星期三', pinyin: 'xīng qī sān', emoji: '🌄', img: './wednesday.png', en: 'Wednesday', isCore: false, isCCG: true },
      { id: 'Thursday', hanzi: '星期四', pinyin: 'xīng qī sì', emoji: '🌄', img: './thursday.png', en: 'Thursday', isCore: false, isCCG: true },
      { id: 'Friday', hanzi: '星期五', pinyin: 'xīng qī wǔ', emoji: '🌄', img: './friday.png', en: 'Friday', isCore: false, isCCG: true },
      { id: 'Saturday', hanzi: '星期六', pinyin: 'xīng qī liù', emoji: '🌄', img: './saturday.png', en: 'Saturday', isCore: false, isCCG: true },
      { id: 'Sunday', hanzi: '星期天', pinyin: 'xīng qī tiān', emoji: '🌄', img: './sunday.png', en: 'Sunday', isCore: false, isCCG: true },
      { id: 'time1', hanzi: '一点', pinyin: 'yī diǎn', emoji: '🕐', en: '1 o\'clock', isCore: true, isCCG: true },
      { id: 'time2', hanzi: '两点', pinyin: 'liǎng diǎn', emoji: '🕑', en: '2 o\'clock', isCore: true, isCCG: true },
      { id: 'time3', hanzi: '三点', pinyin: 'sān diǎn', emoji: '🕒', en: '3 o\'clock', isCore: true, isCCG: true },
      { id: 'time4', hanzi: '四点', pinyin: 'sì diǎn', emoji: '🕓', en: '4 o\'clock', isCore: true, isCCG: true },
      { id: 'time5', hanzi: '五点', pinyin: 'wǔ diǎn', emoji: '🕔', en: '5 o\'clock', isCore: true, isCCG: true },
      { id: 'time6', hanzi: '六点', pinyin: 'liù diǎn', emoji: '🕕', en: '6 o\'clock', isCore: true, isCCG: true },
      { id: 'time7', hanzi: '七点', pinyin: 'qī diǎn', emoji: '🕖', en: '7 o\'clock', isCore: true, isCCG: true },
      { id: 'time8', hanzi: '八点', pinyin: 'bā diǎn', emoji: '🕗', en: '8 o\'clock', isCore: true, isCCG: true },
      { id: 'time9', hanzi: '九点', pinyin: 'jiǔ diǎn', emoji: '🕘', en: '9 o\'clock', isCore: true, isCCG: true },
      { id: 'time10', hanzi: '十点', pinyin: 'shí diǎn', emoji: '🕙', en: '10 o\'clock', isCore: true, isCCG: true },
      { id: 'time11', hanzi: '十一点', pinyin: 'shí yī diǎn', emoji: '🕚', en: '11 o\'clock', isCore: true, isCCG: true },
      { id: 'time12', hanzi: '十二点', pinyin: 'shí èr diǎn', emoji: '🕛', en: '12 o\'clock', isCore: true, isCCG: true }
    ]
  },
  professions: {
    id: 'professions', name: '职业', nameEn: 'Professions', icon: '👨‍🔧',
    items: [
      { id: 'teacher', hanzi: '老师', pinyin: 'lǎo shī', emoji: '👩‍🏫', en: 'teacher', isCore: true, isCCG: true },
      { id: 'student', hanzi: '学生', pinyin: 'xué sheng', emoji: '👩‍🎓', en: 'student', isCore: true, isCCG: true },
      { id: 'doctor', hanzi: '医生', pinyin: 'yī shēng', emoji: '👨‍⚕️', en: 'doctor', isCore: true, isCCG: true },
      { id: 'nurse', hanzi: '护士', pinyin: 'hù shi', emoji: '🏥', img: './nurse.png', en: 'nurse', isCore: true, isCCG: false },
      { id: 'police', hanzi: '警察', pinyin: 'jǐng chá', emoji: '👮', en: 'police', isCore: true, isCCG: true },
      { id: 'principal', hanzi: '校长', pinyin: 'xiào zhǎng', emoji: '👨‍💼', en: 'principal', isCore: true, isCCG: true },
      { id: 'driver', hanzi: '司机', pinyin: 'sī jī', emoji: '🚕', img: './driver.png', en: 'driver', isCore: true, isCCG: false },
      { id: 'manager', hanzi: '经理', pinyin: 'jīng lǐ', emoji: '💼',img: './manager.png', en: 'manager', isCore: true, isCCG: false },
      { id: 'waiter', hanzi: '服务员', pinyin: 'fú wù yuán', emoji: '💁', en: 'waiter/waitress', isCore: true, isCCG: false },
      { id: 'classmate', hanzi: '同学', pinyin: 'tóng xué', emoji: '🏫', img: './classmate.png', en: 'classmate', isCore: true, isCCG: false },
      { id: 'friend', hanzi: '朋友', pinyin: 'péng you', emoji: '🤝', en: 'friend', isCore: true, isCCG: true },
      { id: 'lawyer', hanzi: '律师', pinyin: 'lǜ shī', emoji: '⚖️', en: 'lawyer', isCore: false, isCCG: true },
      { id: 'firefighter', hanzi: '消防员', pinyin: 'xiāo fáng yuán', emoji: '👨‍🚒', en: 'firefighter', isCore: false, isCCG: true },
      { id: 'astronaut', hanzi: '宇航员', pinyin: 'yǔ háng yuán', emoji: '👩‍🚀', en: 'astronaut', isCore: false, isCCG: true },
      { id: 'athlete', hanzi: '运动员', pinyin: 'yùn dòng yuán', emoji: '🏃', en: 'athlete', isCore: false, isCCG: true },
      { id: 'scientist', hanzi: '科学家', pinyin: 'kē xué jiā', emoji: '🧪', en: 'scientist', isCore: false, isCCG: true },
      { id: 'artist', hanzi: '艺术家', pinyin: 'yì shù jiā', emoji: '🎨', en: 'artist', isCore: false, isCCG: true }
    ]
  },
  daily_life: {
    id: 'daily_life', name: '日常生活', nameEn: 'Daily Life', icon: '🏠',
    items: [
      { id: 'get_up', hanzi: '起床', pinyin: 'qǐ chuáng', emoji: '⏰', img: './get_up.png', en: 'get up', isCore: true, isCCG: true },
      { id: 'sleep', hanzi: '睡觉', pinyin: 'shuì jiào', emoji: '🛌', en: 'sleep', isCore: true, isCCG: true },
      { id: 'eat_meal', hanzi: '吃饭', pinyin: 'chī fàn', emoji: '🍝', en: 'eat meal', isCore: true, isCCG: true },
      { id: 'study_act', hanzi: '学习', pinyin: 'xué xí', emoji: '📚', en: 'study', isCore: true, isCCG: true },
      { id: 'attend_class', hanzi: '上课', pinyin: 'shàng kè', emoji: '🧑‍🏫', en: 'attend class', isCore: false, isCCG: true },
      { id: 'do_exercise', hanzi: '做运动', pinyin: 'zuò yùn dòng', emoji: '🏃‍♀️', en: 'do exercise', isCore: false, isCCG: true },
      { id: 'do_homework', hanzi: '做作业', pinyin: 'zuò zuò yè', emoji: '✍🏻', en: 'do homework', isCore: false, isCCG: true },
      { id: 'online_class', hanzi: '网课', pinyin: 'wǎng kè', emoji: '👩‍💻', en: 'online class', isCore: false, isCCG: true },
      { id: 'listen_to_music', hanzi: '听音乐', pinyin: 'tīng yīn yuè', emoji: '🎶', en: 'listen to music', isCore: false, isCCG: true },
      { id: 'play_guitar', hanzi: '弹吉他', pinyin: 'tán jí tā', emoji: '🎸', en: 'play guitar', isCore: false, isCCG: true },
      { id: 'work_act', hanzi: '工作', pinyin: 'gōng zuò', emoji: '💼', img: './work.png', en: 'work', isCore: true, isCCG: false },
      { id: 'go_to_school', hanzi: '上学', pinyin: 'shàng xué', emoji: '🎒', img: './go_to_school.png', en: 'go to school', isCore: true, isCCG: true },
      { id: 'finish_school', hanzi: '放学', pinyin: 'fàng xué', emoji: '🚶', img: './finish_school.png', en: 'finish school', isCore: true, isCCG: true },
      { id: 'go_home', hanzi: '回家', pinyin: 'huí jiā', emoji: '🏠', img: './go_home.png', en: 'go home', isCore: true, isCCG: true },
      { id: 'phone_call', hanzi: '打电话', pinyin: 'dǎ diàn huà', emoji: '📞', en: 'make a call', isCore: true, isCCG: true },
      { id: 'shopping_act', hanzi: '买东西', pinyin: 'mǎi dōng xi', emoji: '🛍️', en: 'shopping', isCore: true, isCCG: true },
      { id: 'singing', hanzi: '唱歌', pinyin: 'chàng gē', emoji: '🎤', en: 'singing', isCore: true, isCCG: true },
      { id: 'dancing', hanzi: '跳舞', pinyin: 'tiào wǔ', emoji: '💃', en: 'dancing', isCore: true, isCCG: true },
      { id: 'play_games', hanzi: '玩游戏', pinyin: 'wán yóu xì', emoji: '🎮', en: 'play games', isCore: true, isCCG: true },
      { id: 'painting_act', hanzi: '画画', pinyin: 'huà huà', emoji: '🎨', en: 'paint/draw', isCore: true, isCCG: true },
      { id: 'piano_act', hanzi: '弹钢琴', pinyin: 'tán gāng qín', emoji: '🎹', en: 'play piano', isCore: true, isCCG: true },
      { id: 'pray_act', hanzi: '祷告', pinyin: 'dǎo gào', emoji: '🤲', en: 'pray', isCore: false, isCCG: true },
      { id: 'dune_bashing', hanzi: '冲沙', pinyin: 'chōng shā', emoji: '🏜️', en: 'dune bashing', isCore: false, isCCG: true },
      { id: 'tai_chi', hanzi: '打太极拳', pinyin: 'dǎ tài jí quán', emoji: '🥋', en: 'Tai Chi', isCore: false, isCCG: true },
      { id: 'internet_act', hanzi: '上网', pinyin: 'shàng wǎng', emoji: '🌐', en: 'surf online', isCore: true, isCCG: true },
      { id: 'read_book', hanzi: '看书', pinyin: 'kàn shū', emoji: '📖', en: 'reading', isCore: true, isCCG: false },
      { id: 'watch_movie', hanzi: '看电影', pinyin: 'kàn diàn yǐng', emoji: '🎬', img: './watch_movie.png', en: 'watch movie', isCore: true, isCCG: false }
    ]
  },
  subjects: {
    id: 'subjects', name: '科目', nameEn: 'Subjects', icon: '📅',
    items: [
      { id: 'math', hanzi: '数学', pinyin: 'shù xué', emoji: '🔢', en: 'Math', isCore: true, isCCG: true },
      { id: 'pe', hanzi: '体育', pinyin: 'tǐ yù', emoji: '🏃‍♀️', en: 'PE', isCore: true, isCCG: true },
      { id: 'music_sub', hanzi: '音乐', pinyin: 'yīn yuè', emoji: '🎵', en: 'Music', isCore: true, isCCG: true },
      { id: 'art_sub', hanzi: '美术', pinyin: 'měi shù', emoji: '🎨', en: 'Art', isCore: true, isCCG: true },
      { id: 'science', hanzi: '科学', pinyin: 'kē xué', emoji: '🔬', en: 'Science', isCore: true, isCCG: true },
      { id: 'chinese_sub', hanzi: '中文', pinyin: 'zhōng wén', emoji: '🀄️', en: 'Chinese', isCore: true, isCCG: true },
      { id: 'english_sub', hanzi: '英语', pinyin: 'yīng yǔ', emoji: '🔤', en: 'English', isCore: true, isCCG: true },
      { id: 'arabic_sub', hanzi: '阿拉伯语', pinyin: 'ā lā bó yǔ', emoji: 'س', img: './Arabic.png', en: 'Arabic', isCore: true, isCCG: true },
      { id: 'social_study', hanzi: '社会科学', pinyin: 'shè huì kē xué', emoji: '🌍', en: 'Social Study', isCore: false, isCCG: true },
      { id: 'history', hanzi: '历史', pinyin: 'lì shǐ', emoji: '📜', en: 'History', isCore: true, isCCG: false }
    ]
  },
  countries: {
    id: 'countries', name: '国家', nameEn: 'Countries', icon: '🌍',
    items: [
      { id: 'uae_con', hanzi: '阿联酋', pinyin: 'ā lián qiú', emoji: '🇦🇪', img: './UAE.png', en: 'UAE', isCore: false, isCCG: true },
      { id: 'countries', hanzi: '国家', pinyin: 'guó jiā', emoji: '🌍', en: 'Countries', isCore: false, isCCG: true },
      { id: 'china_con', hanzi: '中国', pinyin: 'zhōng guó', emoji: '🇨🇳', img: './China.png', en: 'China', isCore: true, isCCG: true },
      { id: 'egypt_con', hanzi: '埃及', pinyin: 'āi jí', emoji: '🇪🇬', img: './Egypt.png', en: 'Egypt', isCore: false, isCCG: true },
      { id: 'saudi_con', hanzi: '沙特', pinyin: 'shā tè', emoji: '🇸🇦', img: './Saudi_Arabia.png', en: 'Saudi Arabia', isCore: false, isCCG: true },
      { id: 'oman_con', hanzi: '阿曼', pinyin: 'ā màn', emoji: '🇴🇲', img: './Oman.png', en: 'Oman', isCore: false, isCCG: true },
      { id: 'usa_con', hanzi: '美国', pinyin: 'měi guó', emoji: '🇺🇸', img: './USA.png', en: 'USA', isCore: true, isCCG: true },
      { id: 'uk_con', hanzi: '英国', pinyin: 'yīng guó', emoji: '🇬🇧', img: './UK.png', en: 'UK', isCore: true, isCCG: true },
      { id: 'france_con', hanzi: '法国', pinyin: 'fǎ guó', emoji: '🇫🇷', img: './France.png', en: 'France', isCore: true, isCCG: true },
      { id: 'brazil_con', hanzi: '巴西', pinyin: 'bā xī', emoji: '🇧🇷', img: './Brazil.png', en: 'Brazil', isCore: true, isCCG: true },
      { id: 'india_con', hanzi: '印度', pinyin: 'yìn dù', emoji: '🇮🇳', img: './India.png', en: 'India', isCore: true, isCCG: true },
      { id: 'spain_con', hanzi: '西班牙', pinyin: 'xī bān yá', emoji: '🇪🇸', img: './Spain.png', en: 'Spain', isCore: true, isCCG: true },
      { id: 'australia_con', hanzi: '澳大利亚', pinyin: 'ào dà lì yà', emoji: '🇦🇺', img: './Australia.png', en: 'Australia', isCore: true, isCCG: true },
      { id: 'russia_con', hanzi: '俄罗斯', pinyin: 'é luó sī', emoji: '🇷🇺', img: './Russia.png', en: 'Russia', isCore: true, isCCG: true },
      { id: 'kenya_con', hanzi: '肯尼亚', pinyin: 'kěn ní yà', emoji: '🇰🇪', img: './Kenya.png', en: 'Kenya', isCore: false, isCCG: true },
      { id: 'jordan_con', hanzi: '约旦', pinyin: 'yuē dàn', emoji: '🇯🇴', img: './Jordan.png', en: 'Jordan', isCore: false, isCCG: true },
      { id: 'lebanon_con', hanzi: '黎巴嫩', pinyin: 'lí bā nèn', emoji: '🇱🇧', img: './Lebanon.png', en: 'Lebanon', isCore: false, isCCG: true },
      { id: 'japan_con', hanzi: '日本', pinyin: 'rì běn', emoji: '🇯🇵', img: './Japan.png', en: 'Japan', isCore: true, isCCG: true },
      { id: 'qatar_con', hanzi: '卡塔尔', pinyin: 'kǎ tǎ ěr', emoji: '🇶🇦', img: './Qatar.png', en: 'Qatar', isCore: false, isCCG: true }
    ]
  },
  Customized: {
    id: 'Customized_Words', name: '定制词', nameEn: 'Customized Words', icon: '🎇',
    items: [
      { id: 'jigsaw_puzzle', hanzi: '拼图', pinyin: 'pīn tú', emoji: '🧩', en: 'jigsaw puzzle', isCore: false, isCCG: true },
      { id: 'blocks', hanzi: '积木', pinyin: 'jī mù', emoji: '🧱', img: './blocks.png', en: 'blocks', isCore: false, isCCG: true },
      { id: 'doll', hanzi: '娃娃', pinyin: 'wá wa', emoji: '🪆', en: 'doll', isCore: false, isCCG: true }
    ]
  }
};
